
#  spring.application.name=Post-Reply
#    jwt.secret=mySecretKey123456789123456789123456789123456789
#    spring.data.mongodb.uri=mongodb+srv://user:cxz123@cluster0.wxsizfb.mongodb.net/PostReply?retryWrites=true&w=majority&appName=Cluster0

SECRET_KEY: mySecretKey
spring:
  application:
    name: Post-Reply
  data:
    mongodb:
      uri: mongodb+srv://user:cxz123@cluster0.wxsizfb.mongodb.net/PostReply?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8083
